name: Deploy AWS SAM Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Install AWS SAM CLI
      run: |
        curl -Lo sam-cli-linux-x86_64.zip https://github.com/aws/aws-sam-cli/releases/download/v1.40.0/aws-sam-cli-linux-x86_64.zip
        unzip sam-cli-linux-x86_64.zip -d /usr/local/bin

    - name: Build and deploy using AWS SAM
      run: |
        sam build
        sam deploy --guided
